#page title
page_title                                : Rock Identifier App - iOS & macOS    # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6743698832                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://rockidentifier.net                # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Identify stones, gems and jewelry in seconds with RockPic — our AI-powered scanner app. Just upload a picture to get accurate insights about any kind of rock.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Pablo & Raf
your_link                                 : https://twitter.com/ppacie                     
your_city                                 :                                 
email_address                             : 
linkedin_username                         :                                           
linkedin_company                          :                                           
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : ppacie
github_username                           : ppacie
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : AI Rock Scanner
    description                           : Take a picture or upload from your photo library, and our gemstone scanner will quickly verify the stone.
    fontawesome_icon_name                 : magic
    
  - title                                 : Rarity & Magnetism
    description                           : Determine how rare the stone is and whether it has magnetic properties.
    fontawesome_icon_name                 : magnet

  - title                                 : Composition & Origin
    description                           : Learn about the rock’s chemical makeup, formation, and history.
    fontawesome_icon_name                 : gem

  - title                                 : Alternative Names & Uses
    description                           : Discover other names for the stone and its common applications in jewellery, construction, and more.
    fontawesome_icon_name                 : list-ol

  - title                                 : Organise Your Collection
    description                           : Build your personal rock collection and track your discoveries.
    fontawesome_icon_name                 : folder

  - title                                 : All-in-One Gem & Fossil Identifier 
    description                           : Works with diamonds, crystals, fossils, minerals, and more precious stones.
    fontawesome_icon_name                 : hammer


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#463F38"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#333333"
feature_text_color                        : "#555555"

feature_icons_foreground_color            : "#463F38"
feature_icons_background_color            : "#DBD2BE"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
